export default {
  baseUrl: 'https://api.toptierlessons.com:4436/api/v1.0/',
  getAllSports: 'Sport/GetAllSport',
  geAllSkills: 'Admin/GetAllSkills',
  logIn: 'Auth/SignIn',
  register: 'Auth/Register',
  forgotPassword: 'Auth/ForgotPassword',
  changePassword: 'Auth/ChangePassword',
  uploadProfilePic: 'User/UpdateProfilePic',
  updateProfile: 'User/UpdateUserProfile',
  getUserProfile: 'User/GetUserProfile',
  getNearVenue: 'Sport/GetNearbyVenue',
  getAllTimeSlots: 'TimeSlots/GetAllTimeSlots',
  deleteTimeSlot: 'TimeSlots/DeleteTimeSlot',
  getSlotById: 'TimeSlots/GetSlotById',
  addSlot: 'TimeSlots/AddTimeSlot',
  updateSlot: 'TimeSlots/UpdateTimeSlot',
  uploadFile: 'User/UploadFile',
  documentUpload: 'Document/UploadDocument',
  deleteVenue: 'Venue/DeleteCoachVenue',
  previousBookings: 'Booking/GetBookingHistory',
  upcomingBookings: 'Booking/GetUpComingBookings',
  updateBookingStatus: 'Booking/UpdateBookingStatus',
};
