export default {
  SPLASH: 'SPLASH',
  ONBOARDING: 'ONBOARDING',
  LOGIN: 'LOGIN',
  FORGOTPASSWORD: 'FORGOTPASSWORD',
  NEWPASSWORD: 'NEWPASSWORD',
  RESETPASSWORD: 'RESETPASSWORD',
  REGISTER: 'REGISTER',
  USERPROFILESETUP: 'USERPROFILESETUP',
  COACHPROFILESETUP: 'COACHPROFILESETUP'
};
